version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=${TSB_AIRFLOW_DATABASE_NAME:-airflow_db}
      - POSTGRESQL_USERNAME=${TSB_AIRFLOW_DATABASE_USERNAME:-airflow_usr}
      - POSTGRESQL_PASSWORD=${DB_PASS:-1122334455AABBCCDD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=${TSB_AIRFLOW_DATABASE_NAME:-airflow_db}
      - AIRFLOW_DATABASE_USERNAME=${TSB_AIRFLOW_DATABASE_USERNAME:-airflow_usr}
      - AIRFLOW_DATABASE_PASSWORD=${DB_PASS:-1122334455AABBCCDD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=${TSB_AIRFLOW_DATABASE_NAME:-airflow_db}
      - AIRFLOW_DATABASE_USERNAME=${TSB_AIRFLOW_DATABASE_USERNAME:-airflow_usr}
      - AIRFLOW_DATABASE_PASSWORD=${TSB_AIRFLOW_DATABASE_PASSWORD:-1122334455AABBCCDD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=${TSB_AIRFLOW_DATABASE_NAME:-airflow_db}
      - AIRFLOW_DATABASE_USERNAME=${TSB_AIRFLOW_DATABASE_USERNAME:-airflow_usr}
      - AIRFLOW_DATABASE_PASSWORD=${DB_PASS:-1122334455AABBCCDD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_PASSWORD=${TSB_AIRFLOW_PASSWORD:-1122334455AABBCCDD}
      - AIRFLOW_USERNAME=${TSB_AIRFLOW_USERNAME:-admin}
      - AIRFLOW_EMAIL=${TSB_AIRFLOW_EMAIL:-noreply@tsbberlin.de}
      - AIRFLOW__SMTP__SMTP_HOST=${TSB_AIRFLOW__SMTP__SMTP_HOST:-tsbberlin.de}
      - AIRFLOW__SMTP__SMTP_USER=${TSB_AIRFLOW__SMTP__SMTP_USER:-noreply@tsbberlin.de}
      - AIRFLOW__SMTP__SMTP_PASSWORD=${TSB_AIRFLOW__SMTP__SMTP_PASSWORD:-your_password}
      - AIRFLOW__SMTP__SMTP_PORT=${TSB_AIRFLOW__SMTP__SMTP_PORT:-587}
    ports:
      - '8080:8080'
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
